development:
  :concurrency: 1
  :url: redis://localhost:6379/0

production:
  :concurrency: 1
  :url: <%= ENV['REDIS_TLS_URL'] %>


# stopeed at 4:00 and changed to just sidekiq

# config/sidekiq.yml
# :schedule:
#   monthly_job:
#     cron: "*/30 * * * *"
#     class: "MonthlyJob"
#     queue: default